// <auto-generated />
using DbConsCoreEf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbConsCoreEf.Migrations
{
    [DbContext(typeof(ConsEfDbContext))]
    [Migration("20201016065803_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DbConsCoreEf.Entities.Alphabet_PtBr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("A");

                    b.Property<string>("B");

                    b.Property<string>("C");

                    b.Property<string>("D");

                    b.Property<string>("E");

                    b.Property<string>("F");

                    b.Property<string>("G");

                    b.Property<string>("H");

                    b.Property<string>("I");

                    b.Property<string>("J");

                    b.Property<string>("K");

                    b.Property<string>("L");

                    b.Property<string>("M");

                    b.Property<string>("N");

                    b.Property<string>("O");

                    b.Property<string>("P");

                    b.Property<string>("Q");

                    b.Property<string>("R");

                    b.Property<string>("S");

                    b.Property<string>("T");

                    b.Property<string>("U");

                    b.Property<string>("V");

                    b.Property<string>("W");

                    b.Property<string>("X");

                    b.Property<string>("Y");

                    b.Property<string>("Z");

                    b.HasKey("Id");

                    b.ToTable("alphPtBrs");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.A001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("A");

                    b.HasKey("Id");

                    b.ToTable("A001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.B001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("B");

                    b.HasKey("Id");

                    b.ToTable("B001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.C001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("C");

                    b.HasKey("Id");

                    b.ToTable("C001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.D001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("D");

                    b.HasKey("Id");

                    b.ToTable("D001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.E001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("E");

                    b.HasKey("Id");

                    b.ToTable("E001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.F001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("F");

                    b.HasKey("Id");

                    b.ToTable("F001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.G001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("G");

                    b.HasKey("Id");

                    b.ToTable("G001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.H001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("H");

                    b.HasKey("Id");

                    b.ToTable("H001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.I001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("I");

                    b.HasKey("Id");

                    b.ToTable("I001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.J001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("J");

                    b.HasKey("Id");

                    b.ToTable("J001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.K001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("K");

                    b.HasKey("Id");

                    b.ToTable("K001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.L001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("L");

                    b.HasKey("Id");

                    b.ToTable("L001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.M001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("M");

                    b.HasKey("Id");

                    b.ToTable("M001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.N001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("N");

                    b.HasKey("Id");

                    b.ToTable("N001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.O001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("O");

                    b.HasKey("Id");

                    b.ToTable("O001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.P001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("P");

                    b.HasKey("Id");

                    b.ToTable("P001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.Q001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Q");

                    b.HasKey("Id");

                    b.ToTable("Q001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.R001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("R");

                    b.HasKey("Id");

                    b.ToTable("R001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.S001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("S");

                    b.HasKey("Id");

                    b.ToTable("S001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.T001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("T");

                    b.HasKey("Id");

                    b.ToTable("T001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.U001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("U");

                    b.HasKey("Id");

                    b.ToTable("U001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.V001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("V");

                    b.HasKey("Id");

                    b.ToTable("V001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.W001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("W");

                    b.HasKey("Id");

                    b.ToTable("W001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.X001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("X");

                    b.HasKey("Id");

                    b.ToTable("X001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.Y001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Y");

                    b.HasKey("Id");

                    b.ToTable("Y001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.Letters.Z001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Z");

                    b.HasKey("Id");

                    b.ToTable("Z001s");
                });

            modelBuilder.Entity("DbConsCoreEf.Entities.WordList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Word");

                    b.HasKey("Id");

                    b.ToTable("wordLists");
                });
#pragma warning restore 612, 618
        }
    }
}
